# Generated by Django 5.0.7 on 2026-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandasset',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20),
        ),
    ]
