# Generated by Django 5.0.7 on 2026-08-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_assets', '0002_brandasset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='brand_templates/thumbnails/')),
                ('file', models.FileField(blank=True, null=True, upload_to='brand_templates/files/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='brand_assets.assetcategory')),
            ],
        ),
    ]
