# Generated by Django 5.0.7 on 2026-08-07 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_assets', '0003_brandtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brandasset',
            name='asset_type',
            field=models.CharField(choices=[('BUSINESS_NAME', 'Business Name'), ('SLOGAN', 'Slogan'), ('LOGO', 'Logo'), ('LOGO_PROMPT', 'Logo Prompt'), ('BRAND_GUIDELINE', 'Brand Guideline'), ('SOCIAL_POST', 'Social Post'), ('SOCIAL_GRAPHIC', 'Social Graphic'), ('AD_CREATIVE', 'Ad Creative'), ('POSTER', 'Poster'), ('BANNER', 'Banner'), ('BUSINESS_CARD', 'Business Card'), ('LETTERHEAD', 'Letterhead'), ('EMAIL_HEADER', 'Email Header'), ('CAMPAIGN', 'Campaign'), ('MARKETING_COPY', 'Marketing Copy'), ('NAME', 'Business Name (Legacy)'), ('TAGLINE', 'Tagline (Legacy)'), ('STORY', 'Brand Story (Legacy)'), ('PERSONALITY', 'Personality (Legacy)'), ('VOICE', 'Brand Voice (Legacy)'), ('COLOR', 'Color Palette (Legacy)'), ('TYPOGRAPHY', 'Typography Set (Legacy)')], default='SOCIAL_POST', max_length=50),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='brand_assets/thumbnails/'),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='brandasset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand_assets.assetcategory'),
        ),
        migrations.AlterField(
            model_name='brandasset',
            name='status',
            field=models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged')], default='READY', max_length=20),
        ),
        migrations.AlterField(
            model_name='brandasset',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
