# Generated by Django 5.0.7 on 2026-08-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_assets', '0004_brandasset_asset_type_brandasset_is_selected_and_more'),
        ('branding', '0004_delete_generatedasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandasset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='branding.brandproject'),
        ),
    ]
