# Generated by Django 5.0.7 on 2026-08-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_assets', '0005_alter_brandasset_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandasset',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
