# Generated by Django 5.0.7 on 2026-08-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_assets', '0006_brandasset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandasset',
            name='asset_type',
            field=models.CharField(choices=[('BUSINESS_NAME', 'Business Name'), ('SLOGAN', 'Slogan'), ('LOGO', 'Logo'), ('LOGO_PROMPT', 'Logo Prompt'), ('BRAND_GUIDELINE', 'Brand Guideline'), ('SOCIAL_POST', 'Social Post'), ('SOCIAL_GRAPHIC', 'Social Graphic'), ('AD_CREATIVE', 'Ad Creative'), ('POSTER', 'Poster'), ('BANNER', 'Banner'), ('BUSINESS_CARD', 'Business Card'), ('LETTERHEAD', 'Letterhead'), ('EMAIL_HEADER', 'Email Header'), ('CAMPAIGN', 'Campaign'), ('MARKETING_COPY', 'Marketing Copy'), ('NAME', 'Business Name (Legacy)'), ('TAGLINE', 'Tagline (Legacy)'), ('STORY', 'Brand Story (Legacy)'), ('PERSONALITY', 'Personality (Legacy)'), ('VOICE', 'Brand Voice (Legacy)'), ('COLOR', 'Color Palette (Legacy)'), ('TYPOGRAPHY', 'Typography Set (Legacy)')], db_index=True, default='SOCIAL_POST', max_length=50),
        ),
    ]
