# Generated by Django 5.2.16 on 2026-08-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitylogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='project',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
    ]
