# Generated by Django 5.2.16 on 2026-07-31 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand_assets', '0001_initial'),
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter'), ('LINKEDIN', 'LinkedIn'), ('FACEBOOK', 'Facebook')], max_length=20)),
                ('caption', models.TextField()),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand_assets.brandasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='branding.brandproject')),
            ],
        ),
    ]
