# Generated by Django 5.2.16 on 2026-07-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('TEXT', 'Text Generation (LLM)'), ('IMAGE', 'Image Generation (Diffusion)'), ('EMBEDDING', 'Embedding Model (RAG)')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('provider_name', models.CharField(default='HuggingFace', help_text='e.g., OpenAI, Anthropic, Custom', max_length=100)),
                ('api_identifier', models.CharField(help_text='Model path or key name used to call the API', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (In Production)'), ('INACTIVE', 'Inactive'), ('TESTING', 'Testing (A/B)'), ('DEPRECATED', 'Deprecated')], default='INACTIVE', max_length=20)),
                ('is_fine_tuned', models.BooleanField(default=False)),
                ('performance_score', models.FloatField(blank=True, help_text='Average accuracy or preference rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
