# Generated by Django 5.0.7 on 2026-08-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key for the model', max_length=255, null=True),
        ),
    ]
