# Generated by Django 5.0.7 on 2026-08-08 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branding', '0004_delete_generatedasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('BRAND', 'Brand Template'), ('CAMPAIGN', 'Campaign Template'), ('MARKETING', 'Marketing Template'), ('SOCIAL', 'Social Template'), ('EMAIL', 'Email Template'), ('POSTER', 'Poster Template')], max_length=20)),
                ('content_payload', models.JSONField()),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('source_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='branding.brandproject')),
            ],
        ),
    ]
