# Generated by Django 5.0.7 on 2026-08-07 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_assets', '0005_alter_brandasset_project'),
        ('campaigns', '0001_initial'),
        ('marketing', '0002_marketingcontent_content_json_and_more'),
        ('socialmedia', '0002_socialpost_content_json_socialpost_model_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='timeline',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='asset_link',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='content_strategy',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_audience',
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_pillars',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platforms',
            field=models.JSONField(blank=True, help_text='List of target platforms', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_day', models.IntegerField(help_text='Day of the campaign (e.g., 1, 3, 5)')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('objective', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('GENERATED', 'Generated'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campaigns.campaign')),
                ('creative_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_items', to='brand_assets.brandasset')),
                ('marketing_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_items', to='marketing.marketingcontent')),
                ('social_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_items', to='socialmedia.socialpost')),
            ],
            options={
                'ordering': ['scheduled_day'],
            },
        ),
    ]
