# Generated by Django 5.0.7 on 2026-08-08 04:09

import brand_reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branding', '0004_delete_generatedasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('STRATEGY', 'Brand Strategy'), ('IDENTITY', 'Brand Identity'), ('AUDIT', 'Brand Audit'), ('CAMPAIGN', 'Campaign Report'), ('EXECUTIVE', 'Executive Brand Report'), ('GUIDELINES', 'Brand Guidelines')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='GENERATING', max_length=20)),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of the data used to generate this report.')),
                ('file', models.FileField(blank=True, null=True, upload_to=brand_reports.models.report_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='branding.brandproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'report_type', 'version')},
            },
        ),
    ]
