# Generated by Django 5.0.7 on 2026-08-05 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_generatedasset_status'),
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='branding.brandproject'),
        ),
    ]
