from ai_services.services import AIService
from marketing.models import MarketingContent

class MarketingAgent:
    def generate_ad(self, project_id, goal, platform, offer, details, cta_style):
        prompt = f"Create an ad for {platform} with goal: {goal}. Offer: {offer}. Details: {details}. CTA style: {cta_style}. Return JSON with 'headline', 'body', 'cta'."
        return AIService.generate_structured(prompt)

    def generate_email(self, project_id, purpose, topic, offer):
        prompt = f"Create an email for {purpose}. Topic: {topic}. Offer: {offer}. Return JSON with 'subject', 'body'."
        return AIService.generate_structured(prompt)

    def generate_landing_page(self, project_id, goal, product, details):
        prompt = f"Create a landing page for {product}. Goal: {goal}. Details: {details}. Return JSON with 'hero_headline', 'hero_subheadline', 'features' (list), 'cta'."
        return AIService.generate_structured(prompt)

    def generate_blog(self, project_id, topic, goal, length, keywords):
        prompt = f"Create a blog post on {topic}. Goal: {goal}, Length: {length}, Keywords: {keywords}. Return JSON with 'title', 'content', 'meta_description'."
        return AIService.generate_structured(prompt)

    def generate_seo(self, project_id, topic, primary_keyword, secondary_keywords):
        prompt = f"Create SEO metadata for {topic}. Primary: {primary_keyword}, Secondary: {secondary_keywords}. Return JSON with 'title_tag', 'meta_description', 'h1', 'keywords' (list)."
        return AIService.generate_structured(prompt)

class MarketingGenerationService:
    @staticmethod
    def generate(user, project, content_type, **kwargs):
        agent = MarketingAgent()
        result = None
        title = ""
        
        # Build prompt_metadata from kwargs to save in DB
        prompt_metadata = kwargs.copy()
        
        if content_type == 'AD':
            result = agent.generate_ad(
                project_id=project.id,
                goal=kwargs.get('goal', ''),
                platform=kwargs.get('platform', ''),
                offer=kwargs.get('offer', ''),
                details=kwargs.get('details', ''),
                cta_style=kwargs.get('cta_style', '')
            )
            title = f"{kwargs.get('platform')} Ad: {kwargs.get('offer')}"
            
        elif content_type == 'EMAIL':
            result = agent.generate_email(
                project_id=project.id,
                purpose=kwargs.get('purpose', ''),
                topic=kwargs.get('topic', ''),
                offer=kwargs.get('offer', '')
            )
            title = f"Email: {kwargs.get('topic')}"
            
        elif content_type == 'LANDING_PAGE':
            result = agent.generate_landing_page(
                project_id=project.id,
                goal=kwargs.get('goal', ''),
                product=kwargs.get('product', ''),
                details=kwargs.get('details', '')
            )
            title = f"Landing Page: {kwargs.get('product')}"
            
        elif content_type == 'BLOG':
            result = agent.generate_blog(
                project_id=project.id,
                topic=kwargs.get('topic', ''),
                goal=kwargs.get('goal', ''),
                length=kwargs.get('length', ''),
                keywords=kwargs.get('keywords', '')
            )
            title = f"Blog: {kwargs.get('topic')}"
            
        elif content_type == 'SEO':
            result = agent.generate_seo(
                project_id=project.id,
                topic=kwargs.get('topic', ''),
                primary_keyword=kwargs.get('primary_keyword', ''),
                secondary_keywords=kwargs.get('secondary_keywords', '')
            )
            title = f"SEO: {kwargs.get('topic')}"
            
        if not result:
            if content_type == 'AD':
                result = {'headline': f"Check out {kwargs.get('offer')}", 'body': f"We are offering {kwargs.get('details')}", 'cta': "Learn More"}
            elif content_type == 'EMAIL':
                result = {'subject': f"Update on {kwargs.get('topic')}", 'body': f"Here is the latest about {kwargs.get('offer')}"}
            elif content_type == 'LANDING_PAGE':
                result = {'hero_headline': f"Welcome to {kwargs.get('product')}", 'hero_subheadline': f"Goal: {kwargs.get('goal')}", 'features': [kwargs.get('details', 'Feature 1')], 'cta': "Get Started"}
            elif content_type == 'BLOG':
                result = {'title': f"All about {kwargs.get('topic')}", 'content': "This is a fallback blog content generated by the system.", 'meta_description': f"A short post about {kwargs.get('topic')}"}
            elif content_type == 'SEO':
                result = {'title_tag': f"{kwargs.get('topic')} | {project.business_name}", 'meta_description': "SEO description fallback.", 'h1': kwargs.get('topic', 'Topic'), 'keywords': [kwargs.get('primary_keyword', 'keyword')]}

        if result:
            content = MarketingContent.objects.create(
                user=user,
                project=project,
                content_type=content_type,
                title=title[:255],
                content_json=result,
                status='GENERATED',
                prompt_metadata=prompt_metadata
            )
            return content
        return None

class ContentRefinementService:
    @staticmethod
    def refine_content(user, project, existing_content, operation):
        from ai_services.services import AIService
        from ai_services.context import BrandContextService
        import json
        
        context = BrandContextService.get_context(project.id)
        
        system_message = f"""
        You are a Content Refinement Engine for {context.get('business_name')}.
        Brand Voice: {context.get('voice')}
        """
        
        prompt = f"""
        Operation requested: {operation.upper()}
        
        Here is the existing content:
        {json.dumps(existing_content.content_json, indent=2)}
        
        Refine the content based on the operation requested, maintaining the exact same JSON key structure.
        Return ONLY valid JSON.
        """
        
        result = AIService.generate_structured(prompt, system_message)
        if result:
            existing_content.content_json = result
            existing_content.save()
            return existing_content
        return None
