# Generated by Django 5.0.7 on 2026-08-08 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branding', '0004_delete_generatedasset'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('item_type', models.CharField(help_text='e.g., Logo, Social Post, Campaign', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_items', to='branding.brandproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reason', models.TextField(help_text='AI explanation for why this is recommended')),
                ('estimated_minutes', models.IntegerField(default=2)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_recommendations', to='branding.brandproject')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('SETUP', 'Brand Setup'), ('DNA', 'Brand DNA'), ('LOGO', 'Logo'), ('IDENTITY', 'Identity'), ('CREATIVE', 'Creative Assets'), ('MARKETING', 'Marketing'), ('SOCIAL', 'Social'), ('CAMPAIGN', 'Campaign'), ('INTELLIGENCE', 'Brand Intelligence'), ('KIT', 'Brand Kit'), ('REPORTS', 'Executive Reports'), ('LAUNCH', 'Launch')], default='SETUP', max_length=20)),
                ('completed_stages', models.JSONField(blank=True, default=list)),
                ('blocked_stages', models.JSONField(blank=True, default=list)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state', to='branding.brandproject')),
            ],
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(help_text='Snapshot of the content data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflow.approvalitem')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('approval_item', 'version_number')},
            },
        ),
    ]
