# Generated by Django 5.0.7 on 2026-08-07 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcontent',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Structured content data', null=True),
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='prompt_metadata',
            field=models.JSONField(blank=True, help_text='Data used to generate this content', null=True),
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='provider',
            field=models.CharField(blank=True, default='Groq', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='GENERATED', max_length=20),
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketingcontent',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
