# Generated by Django 5.2.16 on 2026-08-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimetric',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='apimetric',
            name='method',
        ),
        migrations.RemoveField(
            model_name='apimetric',
            name='response_time_ms',
        ),
        migrations.RemoveField(
            model_name='apimetric',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemerror',
            name='message',
        ),
        migrations.RemoveField(
            model_name='systemerror',
            name='path',
        ),
        migrations.RemoveField(
            model_name='systemerror',
            name='traceback',
        ),
        migrations.RemoveField(
            model_name='systemerror',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemperformance',
            name='cpu_usage_pct',
        ),
        migrations.RemoveField(
            model_name='systemperformance',
            name='disk_usage_pct',
        ),
        migrations.RemoveField(
            model_name='systemperformance',
            name='memory_usage_pct',
        ),
        migrations.AddField(
            model_name='apimetric',
            name='response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemerror',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='systemperformance',
            name='metric',
            field=models.CharField(default='cpu', max_length=255),
        ),
        migrations.AddField(
            model_name='systemperformance',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='apimetric',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
    ]
