# Generated by Django 5.0.7 on 2026-08-07 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branding', '0004_delete_generatedasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_score', models.IntegerField(default=0)),
                ('activation_score', models.IntegerField(default=0)),
                ('content_coverage_score', models.IntegerField(default=0)),
                ('campaign_readiness_score', models.IntegerField(default=0)),
                ('consistency_score', models.IntegerField(default=0, help_text='AI evaluated consistency 0-100')),
                ('overall_score', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('priority_actions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('NOT_RUN', 'Not Run'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STALE', 'Stale')], default='NOT_RUN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='branding.brandproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrandRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('module_destination', models.CharField(blank=True, help_text='URL name or module constant', max_length=50)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='branding.brandproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
