# Generated by Django 5.2.16 on 2026-07-31 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_idea', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=150, null=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('brand_personality', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_style', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('NAME', 'Business Name'), ('SLOGAN', 'Slogan'), ('TAGLINE', 'Tagline'), ('STORY', 'Brand Story'), ('PERSONALITY', 'Personality'), ('VOICE', 'Brand Voice'), ('COLOR', 'Color Palette'), ('TYPOGRAPHY', 'Typography Set')], max_length=20)),
                ('content', models.JSONField()),
                ('raw_prompt', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='branding.brandproject')),
            ],
        ),
    ]
