# Generated by Django 5.0.7 on 2026-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_generatedasset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandproject',
            name='accent_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='body_font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='brand_mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='brand_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='brand_vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='brand_voice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='business_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='completion_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='generation_status',
            field=models.CharField(default='DRAFT', max_length=50),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='heading_font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='preferred_colors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='primary_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='usp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
