# Generated by Django 5.0.7 on 2026-08-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_brandproject_accent_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedAsset',
        ),
    ]
