# Generated by Django 5.2.16 on 2026-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_delete_generatedasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandproject',
            name='logo_direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandproject',
            name='visual_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
