# Generated by Django 5.2.16 on 2026-07-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key_env_var', models.CharField(default='GET_API_KEY', max_length=100)),
                ('model_name', models.CharField(default='llama-3.1-70b-versatile', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_content', models.TextField(help_text='Use {{ variable }} for injection')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
