# Generated by Django 5.2.16 on 2026-08-17 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
        ('branding', '0004_delete_generatedasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='branding.brandproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branding.brandproject')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ai_services.chatconversation')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=20)),
                ('content', models.TextField()),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_services.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
